### ISSUE TITLE
 ValueError: 'homopolymer_compression.pyx' doesn't match any files

### ISSUE THREAD

**Issue by tseemann** [andrewjpage/tiptoft#11]
Some kind of cython issue?

```
pip3 install tiptoft
Collecting tiptoft
  Downloading https://files.pythonhosted.org/packages/8d/1e/0df98a3565f3f656ca625bc427804de61282593c0fed17fcb14da7605891/tiptoft-0.1.1.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 20.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qkhicklb/tiptoft/setup.py", line 36, in <module>
        ext_modules = cythonize(extensions),
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'homopolymer_compression.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qkhicklb/tiptoft/
```

```
pip3 --version
pip 18.0 from /home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip (python 3.7)

cython --version
Cython version 0.28.5
```

**Comment by andrewjpage** [comment]
The error should be fixed now, I wasnt distributing the cython source files to pypi

**Comment by andrewjpage** [comment]
Its all totally working now.

```
docker run -it linuxbrew/linuxbrew
brew install python3
pip3 install cython
pip3 install tiptoft
```
