### ISSUE TITLE
Error downloading database

### ISSUE THREAD

**Issue by samlipworth** [andrewjpage/tiptoft#26]
tried both conda and pip installations, get the same error. Do you know what causes it?

````
tiptoft_database_downloader plasmidfinder
Downloading data with:
curl -o enterobacteriaceae.fsa https://bitbucket.org/genomicepidemiology/plasmidfinder_db/raw/master/enterobacteriaceae.fsa

Downloading data with:
curl -o gram_positive.fsa https://bitbucket.org/genomicepidemiology/plasmidfinder_db/raw/master/gram_positive.fsa

Combining downloaded fasta files...
    gram_positive.fsa
Traceback (most recent call last):
  File "/gpfs2/well/bag/users/lipworth/python3venv/bin/tiptoft_database_downloader", line 30, in <module>
    tiptoft.run()
  File "/gpfs2/well/bag/users/lipworth/python3venv/lib/python3.4/site-packages/tiptoft/TipToftDatabaseDownloader.py", line 23, in run
    refgenes.run(self.output_prefix)
  File "/gpfs2/well/bag/users/lipworth/python3venv/lib/python3.4/site-packages/tiptoft/RefGenesGetter.py", line 87, in run
    exec('self._get_from_' + self.ref_db + '(outprefix)')
  File "<string>", line 1, in <module>
  File "/gpfs2/well/bag/users/lipworth/python3venv/lib/python3.4/site-packages/tiptoft/RefGenesGetter.py", line 60, in _get_from_plasmidfinder
    for seq in file_reader:
  File "/gpfs2/well/bag/users/lipworth/python3venv/lib/python3.4/site-packages/pyfastaq/sequences.py", line 141, in file_reader
    raise Error('Error determining file type from file "' + fname + '". First line is:\n' + line.rstrip())
pyfastaq.sequences.Error: Error determining file type from file "/gpfs2/well/bag/users/lipworth/gram_neg/gnbc_nanopore/easymag/plasmidfinder.tmp.download/gram_positive.fsa". First line is:
<!DOCTYPE html>
```

**Comment by samlipworth** [comment]
looks like the link to the gram positive file needs updating?

**Comment by andrewjpage** [comment]
Thanks for reporting the issue. I've fixed it now. It will take time for the new version to become available everywhere, but should be in pypi first (pip install tiptoft).
